# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472463cd8d78194b7bf43a307007be84255214ca34345d541ee9acca84c7ca6e1d138e075b4967259600de64c94a996ff2bd9d87d0b6e106bd031aafb5892b6c

test:
  secret_key_base: 67a1c492effa1c9e644f0747442de8637b278eb5a9ac4fd0a1bff9c54f56a7f960a230a30cebe58761d0739e6ae005531f38e5bd7105ffa98163df860112d59c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
